[[pages]]
path = "paginas/inicio.py"
name = "Inicio"
icon = ":house:"

[[pages]]
name = "Campeonatos"
icon = "ğŸ†"
is_section = true

[[pages]]
path = "paginas/competicoes.py"
name = "CompetiÃ§Ã£o"
icon = "ğŸ¥‡"

[[pages]]
path = "paginas/equipes.py"
name = "Equipes"
icon = "ğŸ’ª"

[[pages]]
name = "Ranking Geral"
icon = "ğŸ…"
is_section = true

[[pages]]
path = "paginas/atletas.py"
name = "Atletas"
icon = "â›¹ğŸ¿â€â™‚ï¸"

[[pages]]
path = "paginas/times.py"
name = "Times"
icon = "ğŸ‘Š"
